// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XO5gn6GIXuqx79sSkkD_Gc3oagl6_04',
    appId: '1:257274033337:web:20e39abb892608eea79768',
    messagingSenderId: '257274033337',
    projectId: 'social-media-ed637',
    authDomain: 'social-media-ed637.firebaseapp.com',
    storageBucket: 'social-media-ed637.appspot.com',
    measurementId: 'G-V4XS02MFQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTx2SOeLalD8uXrxqAPe7WBT0NX4y_Oh0',
    appId: '1:257274033337:android:0044856726a82e62a79768',
    messagingSenderId: '257274033337',
    projectId: 'social-media-ed637',
    storageBucket: 'social-media-ed637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVVFBRQjYglObiymbpkHkBZwevTgV84Zc',
    appId: '1:257274033337:ios:803061c21f70687fa79768',
    messagingSenderId: '257274033337',
    projectId: 'social-media-ed637',
    storageBucket: 'social-media-ed637.appspot.com',
    iosClientId:
        '257274033337-f5i0f88pkbrq3gh7vpslaq8nqel7jovb.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNetworkNewsfeed',
  );
}
